import{a as v,S,i as n}from"./assets/vendor-SA7bT8CU.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const q="55202338-7fca1a1810bad0a3b47ced76b";async function m(o,t=1){return(await v.get("https://pixabay.com/api/",{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),M=new S(".gallery a");function p(o){const t=o.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r.likes}</p>
          <p><b>Views</b> ${r.views}</p>
          <p><b>Comments</b> ${r.comments}</p>
          <p><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function B(){h.innerHTML=""}function g(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function L(){document.querySelector(".load-more").classList.remove("hidden")}function d(){document.querySelector(".load-more").classList.add("hidden")}const f=document.querySelector(".form"),P=document.querySelector(".load-more");let c="",a=1,u=0;const w=15;f.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!!c){a=1,B(),d(),g();try{const t=await m(c,a);if(t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}u=t.totalHits,p(t.hits),u>w?L():n.info({message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Something went wrong!"})}finally{b(),f.reset()}}});P.addEventListener("click",async()=>{a+=1,d(),g();try{const o=await m(c,a);p(o.hits);const t=Math.ceil(u/w);a>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):L();const r=document.querySelector(".gallery-item");if(r){const{height:i}=r.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{n.error({message:"Something went wrong!"})}finally{b()}});
//# sourceMappingURL=index.js.map
